### ISSUE TITLE
Nan 

### ISSUE THREAD

**Issue by csyanghan** [zz10001/LITS2017-main1#5]
Can you help me with this!!
![image](https://user-images.githubusercontent.com/31543505/121912233-ff617c00-cd62-11eb-988d-13774d4aef3e.png)

**Comment by zz10001** [comment]
what have you changed？

**Comment by csyanghan** [comment]
Thanks for your attention, I change nothing and get this error, then i change the optimizer to SGD, till now(epoch 3), it works well

**Comment by zz10001** [comment]
Sorry, I don't meet it when the optimizer is Adam, and happy heard to this repo works well for you.

**Comment by csyanghan** [comment]
there maybe some problem with the metric calculation as following
![image](https://user-images.githubusercontent.com/31543505/122017343-772bb700-cdf4-11eb-8753-099ba3258720.png)
why multiple the `val` by `n`? As the `loss` `iou` `dice_1` `dice_2` are the sum of the epoch.
![image](https://user-images.githubusercontent.com/31543505/122017735-cffb4f80-cdf4-11eb-9df0-9111f63b07a1.png)

**Comment by csyanghan** [comment]
> Sorry, I don't meet it when the optimizer is Adam, and happy heard to this repo works well for you.

I suggest maybe I removed the tensor of the dice calculation
![image](https://user-images.githubusercontent.com/31543505/122018078-1badf900-cdf5-11eb-92f0-ac00e0c0d9c8.png)
Maybe tensor will be added into the computing graph, which causes the problem when backward

**Comment by zz10001** [comment]
> why multiple the `val` by `n`? As the `loss` `iou` `dice_1` `dice_2` are the sum of the epoch.

Actually, The function of it is take the average, not take the sum as below. And `val*n` just take current values(I guess, because i don't Learn more about it, I just take it according to others)
![image](https://user-images.githubusercontent.com/39954774/122036529-40f73300-ce06-11eb-8022-7c88973cfea5.png)

**Comment by csyanghan** [comment]
I think there is a problem with this way of writing. Take iou for example. Looking at the code, we know that the calculation is the iou of all pictures in this batch_size. It is obviously wrong to calculate according to AverageMeter.

**Comment by zz10001** [comment]
It seems the iou is all pictures in this batch_size according to the code, Thanks for you to figure out it, but I have no time to fix it this time, Maybe you can rebuild it by yourself (0.0

**Comment by csyanghan** [comment]
> Can you help me with this!!
> ![image](https://user-images.githubusercontent.com/31543505/121912233-ff617c00-cd62-11eb-988d-13774d4aef3e.png)

I think it maybe [There are only all 0s in the target](https://blog.csdn.net/qq_36011385/article/details/114278847)

**Comment by zz10001** [comment]
> I think it maybe [There are only all 0s in the target](https://blog.csdn.net/qq_36011385/article/details/114278847)

But I have already removed all 0s in target according to [here](https://github.com/zz10001/LITS2017-main1/blob/4e998254f5ef1d81b07e8196d8026ae3901dd57e/data_prepare/preprocess.py#L86) ---have something wrong..., it seems to have some wrong when saving the npy so that it has the empty mask, you can have a minor change to make all mask is effective.
